[2024-05-10T13:46:55.310+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T13:46:55.319+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_dag.load_data scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-10T13:46:55.322+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_dag.load_data scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-10T13:46:55.322+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-10T13:46:55.326+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-05-09 00:00:00+00:00
[2024-05-10T13:46:55.330+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-10T13:46:55.332+0000] {standard_task_runner.py:63} INFO - Started process 68 to run task
[2024-05-10T13:46:55.332+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '***_dag', 'load_data', 'scheduled__2024-05-09T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9m8eyftz']
[2024-05-10T13:46:55.333+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask load_data
[2024-05-10T13:46:55.354+0000] {task_command.py:426} INFO - Running <TaskInstance: airflow_dag.load_data scheduled__2024-05-09T00:00:00+00:00 [running]> on host d3ab8b417d7c
[2024-05-10T13:46:55.381+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T00:00:00+00:00'
[2024-05-10T13:46:55.382+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T13:47:26.609+0000] {warnings.py:110} WARNING - /opt/***/dags/tasks/load_data.py:143: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df["authorsAffilationCountry"] = selected_df["authors"].apply(

[2024-05-10T13:47:26.611+0000] {warnings.py:110} WARNING - /opt/***/dags/tasks/load_data.py:147: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finished_df["extracted_class"] = ""

[2024-05-10T13:47:26.625+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-10T13:47:26.626+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T13:47:26.634+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=***_dag, task_id=load_data, run_id=scheduled__2024-05-09T00:00:00+00:00, execution_date=20240509T000000, start_date=20240510T134655, end_date=20240510T134726
[2024-05-10T13:47:26.666+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-10T13:47:26.680+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-10T13:47:26.680+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
